**single_single linear_regression**

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
df= pd.read_csv('/content/xAPI-Edu-Data.csv')

In [ ]:
df.head()

gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
0      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
1      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
3      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
4      M          KW       KuwaIT  lowerlevel    G-04         A    IT   

  Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
0        F   Father           15                16                  2   
1        F   Father           20                20                  3   
2        F   Father           10                 7                  0   
3        F   Father           30                25                  5   
4        F   Father           40                50                 12   

   Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
0          20                   Yes                     Good   
1          25                   Yes                     Good   
2          30                    No                      Bad   
3          35                    No                      Bad   
4          50                    No                      Bad   

  StudentAbsenceDays Class  
0            Under-7     M  
1            Under-7     M  
2            Above-7     L  
3            Above-7     L  
4            Above-7     M

In [ ]:
df["id"]=df['GradeID'].str.split("-",expand=True)[1]

In [ ]:
df['id']

0      04
1      04
2      04
3      04
4      04
       ..
475    08
476    08
477    08
478    08
479    08
Name: id, Length: 480, dtype: object

In [ ]:
class mrlr:
  def __init__(self):
    self.b=None
    self.m=None

  def fit(self, x_train, y_train):
    nom=0
    den=0
    for i in range(x_train.shape[0]):
      nom=nom+((x_train[i]-x_train.mean())*(y_train[i]-y_train.mean()))
      den=den+((x_train[i]-x_train.mean())*(x_train[i]-x_train.mean()))

      self.m=nom/den
      self.b=y_train.mean()-(self.m*x_train.mean())
      print(self.m)
      print(self.b)

  def predict(self,x_test):
    print(x_test)
    return self.m*x_test+self.b





In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
df=pd.read_csv("placement (3).csv")

In [ ]:
X = df.iloc[:,0].values
y = df.iloc[:,1].values
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
lr=mrlr()
lr.fit(x_train,y_train)

0.8400666389004626
-2.8680758017493027
0.46924606814696196
-0.2760631884680049
0.4735784832135009
-0.3063464990071707
0.4368114508414633
-0.04934724066615104
0.4903032804315722
-0.42325178626166293
0.4839693968140894
-0.3789783356431844
0.48640320794067066
-0.3959905233047918
0.49703213346001257
-0.47028604837714694
0.4719939239065887
-0.2952705284868111
0.4397481783518019
-0.06987478241794864
0.47590917171947894
-0.3226378659959255
0.5163397239276872
-0.6052448990217885
0.521190861769847
-0.6391540493423702
0.529161602582466
-0.6948690294512763
0.5305281218210268
-0.7044209135213642
0.529922374981655
-0.7001867809733322
0.5639383415253931
-0.9379562611161529
0.5716752372889344
-0.9920366789473216
0.5729455718328632
-1.0009162380134748
0.5740242768181008
-1.0084563184412234
0.5814518869758193
-1.0603748492180411
0.5765851988353474
-1.0263570032841516
0.5726511703244137
-0.9988583898695067
0.5674090514441672
-0.9622163065290139
0.5710666030961015
-0.9877823639790559
0.5722783622204375
-

In [ ]:
print(lr.predict(x_test[0]))


8.58
3.891116009744203


**multi linear regression**

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_diabetes

In [5]:
X,y= load_diabetes(return_X_y=True)

In [7]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [12]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [16]:
class MraLr2:
    def __init__(self):
      self.coef_=None
      self.intercept_=None

    def fit(self,X_train,y_train):
        X_train=np.insert(X_train,0,1,axis=1)
        ci=np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_=ci[0]
        self.coef_=ci[1:]
    def pred(self, X_test):
        y_pred=np.dot(X_test,self.coef_)+self.intercept_
        return y_pred


In [17]:
lr=MraLr2()

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [20]:
lr.fit(X_train,y_train)

In [21]:
lr.pred(X_test)

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [22]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])